[package]
name = "rust_cpu_emulator"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
regex = "1.10.4"
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"] }

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.26"

structopt = "0.3.26"
structopt-derive = "0.4.18"
log = "0.4.22"